ublk-org/ublksrv

- lib/Makefile
Building libublksrv(/lib) requires only one c++ file:
ublksrv_json.cpp, which depends on include/nlohmann/json.hpp.
As doc of nlohmann/json.hpp says, it only requires c++11,
so change cppflags for libublksrv from c++20 to c++11.
Signed-off-by: Ziyang Zhang <ZiyangZhang@linux.alibaba.com>
> Makefile: compile c++ files in lib/ with c++11

- include/ublksrv.h
Compiler error occurs since UINT_MAX is not declared in tgt_loop.c on
gcc 10.2.1. Expliclitly including <climits> header solves the problem.
g++ -c -g -O2 -D_GNU_SOURCE -MMD -I include -fcoroutines -std=c++20 tgt_loop.c -o tgt_loop.o
tgt_loop.c: In function ‘int loop_init_tgt(ublksrv_dev*, int, int, char**)’:
tgt_loop.c:64:27: error: ‘UINT_MAX’ was not declared in this scope
64 |    .max_discard_sectors = UINT_MAX >> 9,
|                           ^~~~~~~~
tgt_loop.c:4:1: note: ‘UINT_MAX’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
3 | #include "ublksrv_tgt.h"
+++ |+#include <climits>
4 |
make: *** [Makefile:20: tgt_loop.o] Error 1
Signed-off-by: ZiyangZhang <ZiyangZhang@linux.alibaba.com>
> tgt_loop: add missing header <climits>

- ublksrv_tgt.cpp
Hi Ming, thanks for a great project!
After figuring out how to build on my (outdated) ubuntu-box
```
export PTHREAD_LIBS="-lpthread"
export CXX=/usr/bin/gcc-11
export LDFLAGS="-lstdc++"
autoreconf -i
./configure
make
```
I noticed this warning:
```
In function ‘int snprintf(char*, size_t, const char*, ...)’,
inlined from ‘void cmd_dev_add_usage(char*)’ at ublksrv_tgt.cpp:609:22:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:35: warning: ‘int __builtin___snprintf_chk(char*, long unsigned int, int, long unsigned int, const char*, ...)’ specified bound 4096 exceeds destination size 4092 [-Wstringop-overflow=]
67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
|          ~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
68 | …
```
> ublksrv_tgt: fix potential buffer overflow when printing usage in help

- tests/common/fio_common
- tests/common/loop_common
- tests/debug/test_dev
- tests/generic/001
- tests/generic/002
- tests/generic/003
- tests/loop/001
- tests/loop/002
- tests/loop/003
- tests/loop/004
- tests/loop/005
- tests/loop/007
- tests/null/001
- tests/null/002
- tests/null/004
- tests/null/005
- tests/qcow2/001
- tests/qcow2/002
- tests/qcow2/021
- tests/qcow2/022
- tests/qcow2/040
- tests/qcow2/041
- tests/run_test.sh
While trying to run the tests present in this project, I saw syntax errors. I realized that this was because my default shell is `zsh` (not `bash`); the scripts are supposed to run under `bash`, but this wasn't happening because the `#!/bin/bash` comment lines were moved below SPDX comment lines. (As a result, the `#!` line was just treated as a plain-old comment.)
This change rearranges these comment lines to address the above issue.
(For what it's worth the kernel's [license rules](https://www.kernel.org/doc/Documentation/process/license-rules.rst) address this particular case -- indicating that, for scripts, the SPDX lines should be placed below the `#!` line.)
> Move SPDX comment line in scripts

- include/ublksrv.h
- lib/ublksrv.c
- lib/ublksrv_cmd.c
- lib/ublksrv_json.cpp
- qcow2/tgt_qcow2.cpp
- tests/common/fio_common
- tests/generic/004
- tests/generic/005
- tests/generic/006
- tests/run_test.sh
- tgt_loop.cpp
- tgt_null.cpp
- ublksrv_tgt.cpp
Hi Ziyang,
v3 is against your v2:
1) support to recovery all targets
2) rebase one master branch, since tests is cleaned up
3) remove the change on existed tests(generic/001, generic/002, generic/003), and just let generic/004-006 cover recover tests; also
extend generic/005 to cover recovery test on all targets.
Please review, and if you are fine, I will pull them into master.
Thanks,
> [V3] ublk: add USER_RECOVERY support 

- demo_event.c
- demo_null.c
- lib/ublksrv.c
- lib/ublksrv_cmd.c
- ublksrv_tgt.cpp
While experimenting with this project, I encountered some errors (most were user error on my part). I've put together this batch of targeted changes to add more detail to some of the error messages I encountered, and to address issues with potential leaks and uninitialized variables that I encountered in other cases.
Specifically:
* `demo_event.c` and `demo_null.c` had some minor potential leaks in a few failure paths.
* Trying to add a device with an unknown type resulted in a `NULL` dereference.
* Added error messages in a few cases that failed silently (e.g., no device type given on the command line).
* Added `errno`/return value to a few error messages (most notably, the error that shows up if `/dev/ublk-control` can't be opened)
* Tweaked logic in `main` to be able to display command …
> Targeted improvements for failure paths (error messages, cleanup)

- demo_event.c
- demo_null.c
- qcow2/qcow2.cpp
- qcow2/qcow2_flush_meta.cpp
- qcow2/qcow2_meta.cpp
- qcow2/tgt_qcow2.cpp
- tgt_loop.cpp
- tgt_null.cpp
- ublksrv_tgt.cpp
This is largely in service of enabling more warnings in the code base.
Signed-off-by: reuben olinsky <reubeno.dev@gmail.com>
> Remove unused variables, labels, functions

- Makefile.am
- build_with_liburing_src
- configure.ac
- qcow2/qcow2.cpp
- qcow2/qcow2.h
- qcow2/qcow2_flush_meta.cpp
- qcow2/qcow2_meta.cpp
- ublksrv_tgt.cpp
This adds additional warnings when configuring with --enable-gcc-warnings.
A few warning types were specifically disabled with TODOs; they would be best to address in separate
changes.
Signed-off-by: reuben olinsky <reubeno.dev@gmail.com>
> Enable more warnings on C++ code

- include/ublksrv_tgt.h
- qcow2/qcow2_flush_meta.cpp
- qcow2/tgt_qcow2.cpp
- tgt_loop.cpp
- tgt_null.cpp
Use more standard coroutine constructs to make the code shorter & easier to follow.
I'm not a coro expert, but maybe some of this was necessary with older compilers. However, looking at RedHat:
- Fedora 36 is the earliest release that has kernel 6.0
- The same Fedora has gcc 12.2.1, which compiles this simpler code just fine
Test Plan:
```
make
./tests/run_test.sh all 10 tests/tmp/
```
> Simplify C++ coroutine usage

- include/ublksrv_tgt.h
building on my Debian 11 system with gcc I get these errors:
```
CXX      ublk-tgt_loop.o
tgt_loop.cpp: In function ‘int loop_init_tgt(ublksrv_dev*, int, int, char**)’:
tgt_loop.cpp:123:27: error: ‘UINT_MAX’ was not declared in this scope
123 |    .max_discard_sectors = UINT_MAX >> 9,
|                           ^~~~~~~~
tgt_loop.cpp:8:1: note: ‘UINT_MAX’ is defined in header ‘<climits>’; did you forget to ‘#include <climits>’?
7 | #include "ublksrv_tgt.h"
+++ |+#include <climits>
8 | 
```
> missing <limits.h> header

- tests/generic/004
- tests/generic/005
- tests/generic/006
Hello! I am playing around with ublk, tried to run some tests - found that some tests fails in my environment (ubuntu 22.04 + custom 6.1 kernel). This commit fixes this small issue. There are other tests in generic, where pluck order is correct, so it may be some stray mistype.
------------------------------------------------------
License identifier messed up script interpreter selection. Thus some tests failed to run.
This commit fixes shebang/license pluck order, so affected tests may run.
> tests/generic: fix invalid shebang

- ublksrv_tgt.cpp
In __cmd_dev_del, when the struct data is specified, the initializer .run_dir is missing. This
has as a result, the ublksrv_stop_io_daemon function not to work correctly. Basically the subsequent
call to ublksrv_get_io_daemon_pid returns with
-EINVAL (-22).
> ublksrv_tgt: Add run_dir in __cmd_dev_del

- lib/ublksrv.c
Result of eventfd() might be zero - this is a valid file descriptor.
Also always return -errno (and 0) from ublksrv_setup_eventfd() and use it for the error message.
> Allow eventfd to be zero

- Makefile.am
- configure.ac
Hello! I have been testing ublksrv with clang compiler, and lost some time trying to understand how to pass proper flags with autotools. This PR contains small fix for the issue. I have tested changes with g++-10, g++-11, g++-12 and clang++-14 up to clang++-16. Unit tests complete successfully.
I am open to any comments concerning this MR and will fix problems, if any.
-------------------------------------
clang/clang++ can compile ublksrv sources, but it doesn't support '-fcoroutines' flag, which is mandatory for older versions of g++ to compile sources with c++20 coroutines support.
This commit changes Makefile.am and configure.ac, in such way, one can build ublksrv sources using clang++.
After selecting c++ compiler, configure script will match $CXX with clang++ or g++, flag …
> Makefile: fix clang compilation

- include/ublk_cmd.h
- lib/ublksrv_cmd.c
- nbd/tgt_nbd.cpp
- qcow2/tgt_qcow2.cpp
- tests/generic/007
- tgt_loop.cpp
- tgt_null.cpp
- ublksrv_tgt.cpp
A new recovery flag, UBLK_F_USER_RECOVERY_FAIL_IO, is being added to ublk_drv at
https://lore.kernel.org/linux-block/20240917002155.2044225-1-ushankar@purestorage.com/
Support the creation of devices with this flag specified (via a new -e flag for ublk add). Add a test to verify that all recovery flag combinations have the expected behavior.
> ublksrv_tgt: add support for UBLK_F_USER_RECOVERY_FAIL_IO

- configure.ac
- include/ublksrv_priv.h
- lib/ublksrv_cmd.c
Some users might mount devtmpfs to a location other than /dev.
This means the /dev/ublk-control device might exist at a different
location on the filesystem.
Similarly /dev/ublkc[0-9] devices might exist in different places.
The macros UBLK_CONTROL and UBLKC_PREFIX configure the locations of
these devices. UBLK_CONTROL is the full name of the control device,
and UBLKC_PREFIX is the parent directory of all ublkc[0-9] devices.
Fixes #74
> Add macros UBLK_CONTROL and UBLKC_PREFIX

- lib/ublksrv.c
- lib/ublksrv_aio.c
There are 2 commits in this request
- First one wraps a defining _GNU_SOURCE under `#ifndef` so we avoid redefinition build errors
- Second one fixes eventfd write() call to use uint64_t at all the places. This fixes error on 32-bit platforms where we were using 4byte wide data type.
> libublksrv: Build fixes for 32-bit systems and external integration

- lib/ublksrv.c
pthread_setaffinity_np() is actually a wrapper around sched_setaffinity(). For our usecase we are trying to set affinity only of the current thread, so we can use sched_setaffinity() as a drop in replacement. This makes code more portable (< glibc2.3.4, bionic) and concise while keeping the functionality same.
> libublksrv: use sched_setaffinity() instead of pthread function

- lib/ublksrv_cmd.c
The syscall [`io_uring_enter`](https://manpages.debian.org/unstable/liburing-dev/io_uring_enter.2.en.html) may return EINTR if it is interrupted by a delivery of a signal.  This was happening to me recently; I saw that the `SIG_PROF` signal fired periodically, which would fail the `ublksrv_ctrl_start_dev()` call (returns -EINTR). The signal is firing due to unrelated circumstances. 
Since __ublksrv_ctrl_cmd already added an SQE, it's easier for ublksrv to handle the error instead of the caller.
Note that I only added support to `__ublksrv_ctrl_cmd` since control commands are likely to be done once on startup. io_urings for handling IO are already expected to loop for IO, so there's no need for ublksrv to explicitly handle the `EINTR`.
Currently the code loops indefinitely. I'm also …
> Handle interrupts in __ublksrv_ctrl_cmd

- include/ublksrv.h
- lib/ublksrv.c
Make this symbol public. I need it for an app that calls directly to /lib64/libublksrv.so
> Make ublksrv_reap_events_uring public

- include/ublksrv.h
- lib/ublksrv.c
There was a bug in the previous patch that used the wrong ring, additionally did not use const in the function signature
causing compiler warnings.
This patch has been verified to work with my application and compile without warnings.
> ublksrv_queue_reap_events: fix signature and use the correct ring

- include/ublksrv.h
- lib/ublksrv_json.cpp
- nbd/tgt_nbd.cpp
- tgt_loop.cpp
Just like `losetup` allows skipping first N bytes on the underlying file, let's have something similar for `tgt_loop`.
> tgt_loop: Introduce device offset

- ublksrv_tgt.cpp
Only targets spawned by "ublk add -t ..." will have a pid-file containing the json buffer for its configuration.
So when creating a different type of target, like ./demo_null, ublksrv_tgt_store_dev_data() is never invoked and thus the buffer in list_one_dev is null and we segfault inside ublksrv_json_dump.
For now, only call into ublksrv_json_dump iff -v is used and we have a buffer else fall-back to ublksrv_ctrl_dump which can handle the json buffer being NULL.
In the future we should move ublksrv_tgt_store_dev_data and ublksrv_tgt_get_dev_data into the public library so that all targets can store the json buffer like the built-in ones can.
To reproduce:
Start a demo_null target then run "ublk list -v" and it will crash.
> list_one_dev: do not call ublksrv_json_dump with no buffer

- include/ublksrv.h
The return value is never checked. Invocations of handle_io_async are expected to call ublksrv_complete_io even in an error occurred, so it's cleaner if that responsibility stays with the target in every case.
Returning void also matches the similar function `submit_bio()` in the kernel.
Fixes #81
> change handle_io_async return type to void

- ublksrv_tgt.cpp
This global variable is set but never used so let's just remove it.
> ublksrv_tgt: get rid of the variable full_cmd

- ublk.cpp
Print the name of the binary we failed to execute as well as strerror(errno) to make it clear why we might fail to run the target binary.
$ sudo ./ublk help -t error
Failed to execve() /data/sahlberg/ublksrv/.libs/ublk.error. No such file or directory
> Improve error message if failing to spawn the target process

- include/ublksrv.h
- include/ublksrv_tgt.h
- nbd/ublk.nbd.cpp
- ublk.loop.cpp
- ublk.null.cpp
There are now no built-in targets so we no longer need (struct ublksrv_tgt_type).usage_for_add
> remove UBLKSRV_TGT_TYPE_* definitions

- tests/common/fio_common
- always run ublk.target executable in foreground, simplify target implementation a lot
- ublk is responsible for starting ublk.target in background, and communicating with ublk.target about
- cleanup the mess of json buffer handling
- add two generic APIs for getting/setting ublksrv_ctrl_dev private data
- obsolete ->recover_tgt(), and three recovery related APIs
> Simplifying & cleanup target

- include/ublksrv.h
- include/ublksrv_priv.h
- lib/ublksrv_cmd.c
- targets/include/ublksrv_tgt.h
- targets/nbd/ublk.nbd.cpp
- targets/ublk.cpp
- targets/ublk.loop.cpp
- targets/ublk.null.cpp
- targets/ublksrv_tgt.cpp
Simplifying & cleanup target implementation:
- always run ublk.{target} executable in foreground, simplify ublk.{target} implementation a lot
- ublk program is responsible for starting ublk.{target} in background, and communicating with ublk.target about device_id created in ublk.{target} via
eventfd
- cleanup the mess of json buffer handling
- add two generic libublksrv APIs for getting/setting ublksrv_ctrl_dev private data
- obsolete ->recover_tgt(), and three recovery related libublksrv APIs
> Target cleanup

- README.rst
- targets/include/ublksrv_tgt.h
- targets/nbd/ublk.nbd.cpp
- targets/ublk.loop.cpp
- targets/ublk.null.cpp
- targets/ublksrv_tgt.cpp
- add ublksrv_tgt_cmd_main() for all targets to share command line processing code
- other misc cleanup
- readme update
- fix target specific usage help
>  target cleanup #2: add ublksrv_tgt_cmd_main()

- lib/ublksrv_json.cpp
Do not store the pid-file in /tmp as the tmp-cleaner might delete it for long running ublk targets.
Move it to /run which is a better location for this.
> Move pidfile from /tmp to /run

- targets/ublksrv_tgt.cpp
The zero copy feature in ublk driver side is still in-progress, and not completed yet, so remove the argument first. And we will add it back after the kernel side feature[1] is merged.
[1] https://lore.kernel.org/linux-block/20250218224229.837848-1-kbusch@meta.com/
That is also the reason why the help command doesn't show zero copy switch.
> targets: remove --zero-copy/-z argument

- tests/run_test.sh
The test code runs the executable from the top directory, which is actually one script, and finally 'lt-ublk' could be generated in .libs/, but 'lt-ublk.${target}' can't be generated in this way, and causes test failure, see issue github #102 when running ublk test on rhel10.
Fixes it by trying to populate 'lt-ublk.${target}' first by running 'ublk.{target} help' command.
> tests: try to populate lt-ublk.{target} first in test code

- tests/common/fio_common
commit b6aaf07 ("info: print the actual flag names for the device flags") changes 'state' position, so __ublk_get_dev_state() need to modify for adapting the change.
Fixes: b6aaf07 ("info: print the actual flag names for the device flags")
> tests: common: fix __ublk_get_dev_state()

- lib/ublksrv_cmd.c
Fixes: 8f2a561 ("Handle interrupts in __ublksrv_ctrl_cmd")
The syscall io_uring_enter may return EINTR if it is interrupted by a delivery of a signal. This can stil occur on the first submit.
This commit moves the previous do-while to a combined io_uring_submit_and_wait, which should ensure the io_uring_wait_cqe never needs to enter the kernel.
> Handle more interrupts in __ublksrv_ctrl_cmd

- lib/ublksrv_cmd.c
- targets/ublk.cpp
- targets/ublksrv_tgt.cpp
- utils/ublk_user_id.c
ublksrv_ctrl_init can exit() if the ublk-control device can't be opened. This can cause ./ublk to wait indefinitely for the device_id to be written to the eventfd between ./ublk and the target program.
- Update ublksrv_ctrl_init to return NULL on all failures
- Update callers of ublksrv_ctrl_init to check if result is NULL.
Bug: #111 
This doesn't fix the general problem of #111 but does make ./ublk more robust
> Don't exit from ublksrv_ctrl_init

- demo_event.c
- demo_null.c
- include/ublksrv.h
- include/ublksrv_priv.h
- lib/ublksrv.c
- lib/ublksrv_cmd.c
- lib/ublksrv_json.cpp
- targets/include/ublksrv_tgt.h
- targets/nbd/ublk.nbd.cpp
- targets/ublk.loop.cpp
- targets/ublk.null.cpp
- targets/ublksrv_tgt.cpp
This series breaks out the much nicer json API from the semi-private ublksrv_tgt.cpp and moves it into the public ublksrv_json.cpp.
It was a little messy-ish because things were entangled but the end result looks pretty ok.
There were a small number of unrelated cleanups as well.
> New json api

- targets/ublk.cpp
Treat ENODEV as success when deleting the control device. This stops "delete dev ? failed -19" to be printed everytime you delete a demo_* style device.
> ublk.cpp: do log error when deleting demo_* devices

- targets/include/ublksrv_tgt.h
Some filesystems and backing devices can report a st.st_blksize far bigger than 4kb which this limit ublk_param_is_valid prevents O_DIRECT from being  used.
Remove this limit to allow ublk.loop to use O_DIRECT for these scenarios.
> ublk_param_is_valid: remove upper limit of 4kb for blocksize

- Makefile.am
- configure.ac
- targets/ublk.nfs.cpp
This adds a LIBNFS based backend to build a target ontop of an NFS file.
This uses libnfs master to be built like this:
./configure --prefix=/usr --enable-pthread
make
sudo make install
And then to create a ublk.nfs device, pointing it to a file on an nfs share:
sudo ./ublk.nfs add -t nfs -n 0 --nfs=nfs://10.10.10.11/data/SNAP-1/100M
> New target for NFS: Ublk.nfs

- targets/nbd/ublk.nbd.cpp
- targets/ublk.loop.cpp
We no longer need to differentiate between setting up a target as a new device or recovering an existing device so this argument is no longer used by the setup function.
Remove the recovery argument.
> LOOP/NBD: remove recovery argument to the setup function

- targets/nbd/ublk.nbd.cpp
- targets/ublk.loop.cpp
- targets/ublk.nfs.cpp
- targets/ublk.null.cpp
- targets/ublksrv_tgt.cpp
All built-in targets print the target-specific help via the call to the helper ublksrv_tgt_cmd_main()
This means that a target does not need to print the full set of all arguments but only those arguments that are unique for that particular target. Instead we can create the printout of all arguments inside ublksrv_tgt.cpp:cmd_usage() by combining the standard arguments that all ublksrv_tgt_cmd_main() consumers support and the extra arguments unique to this target.
This reduces some code duplication but also removes the need to access ublksrv_print_std_opts() and thus one less symbol needs to be accessed by a target.
> Remove the direct use of ublksrv_print_std_opts from targets

- targets/ublk.nfs.cpp
We are not using "struct ublk_io_data.private_data" at all from this target so we do not need to allocate enough memory to store a "struct ublk_io_tgt" in this pointer like like the other targets do.
> NFS: remove call to ublksrv_tgt_set_io_data_size

- targets/ublk.nfs.cpp
We don't need this spinlock anymore.  It was used in early draft versions of the code but we no longer need it in the version committed.
> NFS: remove a spinlock around ublksrv_queue_handled_event()

- doc/ublk.1
- doc/ublk.1.xml
- lib/ublksrv_cmd.c
Update the manpage to indicate we need version 1.20.1 of libiscsi for iscsi support.
Additionally, add a couple of patches to suppress valgrind hits. There are several places where we request data from the kernel
but valgrind has no way of knowing that this initializes the data and it causes valgrind to flag it as uninitialized data.
Fix this / suppress these warnings  by explicitely initializing the buffers before we pass it to the kernel for the kernel to populate.
> Iscsi updates

- include/ublksrv.h
- lib/ublksrv.c
- targets/ublksrv_tgt.cpp
61bd439dafa changed the parameters for the ring to add IORING_SETUP_SINGLE_ISSUER/IORING_SETUP_DEFER_TASKRUN.
But the ring is part of the public API and this can break applications that are not compatible with SINGLE_ISSUER.
Change this to restore ublksrv_queue_init() to the original flag used and create a new ublksrv_queue_init_flags() for applications that want to override/control what flags to use for the queue.
Update the built-in targets to use the flags
IORING_SETUP_COOP_TASKRUN | IORING_SETUP_SINGLE_ISSUER | IORING_SETUP_DEFER_TASKRUN
> Fix regression in ublksrv_queue_init()

- targets/include/ublksrv_tgt.h
- targets/nbd/ublk.nbd.cpp
- targets/ublk.cpp
- targets/ublk.iscsi.cpp
- targets/ublk.loop.cpp
- targets/ublk.nfs.cpp
- targets/ublk.null.cpp
- targets/ublksrv_tgt.cpp
The help text was generated in two different places an was also inconsistent depending on what triggered the help text to be printed.
For example "ublk help" would print all the commands that the utility wrapper supported but none of the type specific arguments
while "ublk help -t TYPE | ublk.TYPE help" would print the type specific arguments but only list the three commands add/recover/help.
This series harmonizes this and moves all the help text generation into a single place and ensures that the help text is consistent
regardless of why we print the help text.
It additionally removes the need for ublksrv_print_std_opts() from being a semi-private function and makes it fully static to ublksrv_tgt.cpp.
Finally it renames ublksrv_tgt_cmd_main() to just ublksrv_main()
> Harmonize help text

- targets/include/ublksrv_tgt.h
- targets/ublk.cpp
- targets/ublksrv_tgt.cpp
We do not need to call this function with devid==-1 if execv fails because we already handle this failure if the file descriptor is just closed and the parentvprocess fails to read the dev_id from the pipe.
Thus make it static and reduce the size of the semi-private API in ublksrv_tgt.cpp.
> Make ublksrv_tgt_send_dev_event static

- configure.ac
libiscsi function check sometimes does not work
after fix:
> iscsi: fix check for libiscsi

- include/ublksrv.h
tgt_data is a 16bit wide field but is being passed as a 32bit wide parameter which is then shifted left by 24bits causing the upper 8bits to fall off. First cast this to a 64bit value prior to shifting to preserve these bits for the usage by the target.
Addresses #156
> Width fix for build_user_data
